import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { NavBarUI } from './components/navbar/navbar-ui';
import NextTopLoader from 'nextjs-toploader';
import { NavigationEvents } from './components/navigation-event/navigation-event';
import { Suspense } from 'react';
import { Toaster } from 'react-hot-toast';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const supabase = createServerComponentClient({ cookies: () => cookieStore });
  const {
    data: { session }
  } = await supabase.auth.getSession();

  console.log('iam rendering');

  return (
    <html lang='en' className='dark'>
      <body className='bg-background'>
        <NextTopLoader />
        <Toaster />
        <Providers>
          <nav className='sticky top-0 bg-default-900/80 backdrop-blur-md z-50'>
            <NavBarUI session={session} />{' '}
          </nav>
          <main className='flex flex-col place-content-center items-center overflow-hidden h-fit'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
